### ISSUE TITLE
NREL-REX causing build failures

### ISSUE THREAD

**Issue by ssolson** [MHKiT-Software/MHKiT-Python#100]
Rebecca on my most recent push it looks as though NREL-Rex is suggesting the test location is outside of the domain.

Could you check out this error message from #91?

![image](https://user-images.githubusercontent.com/13438942/110688444-d13a3200-819e-11eb-888b-4011f9ac1851.png)

**Comment by rpauly18** [comment]
The hindcast team was updating the data and as it turns out we caught a bug in their data. It should be fixed tomorrow morning. I have also asked to see if they have any advice on the 429 To Many Requests error that sporadically happens.

**Comment by rpauly18** [comment]
For the 429 errors, there really is not a fantastic work around. The advice the NREL-Rex team gives is to run the tests using local .h5 files. The can be done easily by flipping the HSDS optional input parameter. I have been assured that there are no more structural changes planned to the data in the cloud- but it would be a risk that we could miss something. The up side would be we would no longer have all the failed tests- which is a high priority.

**Comment by ssolson** [comment]
I would vote to try the random wait prior to calling the function before adding larger files to the repo. Then if the error persist we could still go this route.

Is there an ETA on when they will fix the bug we found?

**Comment by rpauly18** [comment]
Bug should get fixed over night. I have tried the random wait time- but I will try even longer wait times tomorrow.

**Comment by rpauly18** [comment]
looks like this bug is fixed. I will test the wait time some more today.
