### ISSUE TITLE
Build failed for Python 3.9

### ISSUE THREAD

**Issue by ssolson** [MHKiT-Software/MHKiT-Python#106]
@rpauly18  the merge from this morning failed on the build and in a strange way. 

For python 3.7, and 3.8 it passed. Py 3.9 failed on a dateframe assertion  error that the returned multiparameter was not the same size as expected. 

Any idea what is going on here?

![image](https://user-images.githubusercontent.com/13438942/115610889-afa48e00-a2a6-11eb-98cf-81533fda0c75.png)

**Comment by rpauly18** [comment]
I am following up on this and will hopefully have an answer soon.

**Comment by rpauly18** [comment]
closed by https://github.com/MHKiT-Software/MHKiT-Python/pull/107
