### ISSUE TITLE
Travis CI no longer working 

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-Python#109]
It appears that Travis is not longer working. There have been the messages for a while that Travis was moving. Perhaps this is what is causing the issue?

**Comment by rpauly18** [comment]
Travis CI did run and showed up after the run was complete. So appears to be a slightly different issue than on MHKiT-Matlab.

**Comment by rpauly18** [comment]
@ssolson as of June 15th, Travis has migrated to Travis-ci.com, so any commits since then have not been run through travis. Looking into how to migrate over.

**Comment by rpauly18** [comment]
Got it set up. We will need to monitor our credit burn rate. Two runs went through 130 credits. I think we should start exploring other options besides Travis

**Comment by ssolson** [comment]
I will start setting up Github actions fo MHKiT

**Comment by ssolson** [comment]
added in #121
