### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-Python#118]
@ssolson it appears that the new Xarray dependency is creating issues for python 3.7 in Travis (but not on my local computer). I will try to find a work around, but what are your thoughts on removing 3.7 as a supported Python version? 

Issue with me continuing to try and debug the tests is that we are burning through our Travis credits very rapidly.

**Comment by rpauly18** [comment]
It was an incompatibility with numpy 0.21.1 that was causing the issue in Python3.7. I have set a version requirement. We will want to re-visit this issue since it is not the best to prevent numpy version updates long term.

**Comment by ssolson** [comment]
Agreed that not updating numpy will need to be adjusted in the future.

wrt to testing, I have completed a github actions testing for another project which I would like to implement on MHKiT. Github actions allows us to test multiple python versions and operating systems (Windows, linux, mac).

**Comment by rpauly18** [comment]
Good. Github actions was what I was going to suggest we switch to. I have heard god things about it.
