### ISSUE TITLE
WPTO Hindcast Region Selection 

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-Python#131]
From a user - "When I request the data for the white star point (see attached image), which is within the domain I enclosed in red, there is no issues.
When I request data for the black star point  which is outside of the red enclosed area but within the hindcast dataset I get the following error:

rex.utilities.exceptions.ResourceValueError: Latitude, longitude coordinates ([[  45.089521 -126.118386]]) are outsides of the resource domain: ((32.529998779296875, -125.93000030517578), (48.49399948120117, -117.31999969482422))

It seems the first and last points in the list of data points (blue dots in image) are being used to determine the “resource domain” hence the red outlined area in the image. This however, excludes much of the data."

example code - 
[NREL_hindcast_testDomain[1].txt](https://github.com/MHKiT-Software/MHKiT-Python/files/7092077/NREL_hindcast_testDomain.1.txt)

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/50752018/131692298-6f7e9adb-eb60-4331-8f8d-3f076ec1a0d3.png">

**Comment by hivanov-nrel** [comment]
This issue is related specifically to rex. The bounds specified in region_selection are bigger and encompass the available hindcast data. The error message indicates that rex has bounds that are much smaller for some reason. I will let Michael know about this.

**Comment by MRossol** [comment]
@rpauly18  and @hivanov-nrel,

I can't reproduce this in rex, the below tests runs without catching any errors. I ran this against our data on Eagle, the dev HSDS service and the production service (which I think MHKIT is using). 

```
In [23]: for year in range(1979, 2011):
    ...:     with ResourceX(f'/nrel/US_wave/West_Coast/West_Coast_wave_{year}.h5', hsds=True) as f:
    ...:         try:
    ...:             gid = f.lat_lon_gid([[ 45.089521, -126.118386]])
    ...:         except ResourceValueError as ex:
    ...:             print('bad year = {}: {}'.format(year, ex))
    ...:
```

I also want to note that the bounds I get from the West_Coast_wave dataset are:

```
In [15]: lat_min, lon_min
Out[15]: (30.0906, -130.072)
 
In [16]: lat_max, lon_max
Out[16]: (48.8641, -116.889)
```

@hivanov-nrel  can you check what version of rex you are using and make sure coordinates or domains aren't getting shuffled in MHKIT?

**Comment by hivanov-nrel** [comment]
@MRossol I ran this using mhkit 0.4.0 and rex 0.2.64 and I am still getting the error. In MHKit it looks like we dont do anything fancy other than calling rex to extract data from the specified coordinates. Below is a snippet:

```
with MultiYearWaveX(wave_path, **waveKwargs) as rex_waves:
            if isinstance(parameter, list):
                for p in parameter:
                    temp_data = rex_waves.get_lat_lon_df(p,lat_lon)
```

**Comment by MRossol** [comment]
@hivanov-nrel, what wave_path are you using?

**Comment by hivanov-nrel** [comment]
@MRossol see below:
```
if data_type == '3-hour':
            wave_path = f'/nrel/US_wave/'+region+'/'+region+'_wave_*.h5'
elif data_type == '1-hour':
            wave_path = f'/nrel/US_wave/virtual_buoy/'+region+'/'+region+'_virtual_buoy_*.h5'
```

**Comment by MRossol** [comment]
@hivanov-nrel 

What are the exact inputs that are failing? I already tried the West Coast and can't reproduce the error so I'm not sure what to try next...

**Comment by MRossol** [comment]
@rpauly18 It looks like the request you made that failed was for the 1hr Virtual Buoy data, which is a SMALLER domain than the 3-hr spatial wave data. As the error states the location you requested is outside the bounds of the Buoy data we have.

**Comment by rpauly18** [comment]
Thanks @MRossol ! This was a request from a user so I will pass along that message. Is it possible to get the bounds of the virtual buoy data for each region so we can incorporate checks in the MHKiT functions as well?

**Comment by MRossol** [comment]
@rpauly18, You can easily pull them using rex as follows:
```
with WindResourceX(${path_to_domain_file}, hsds=True) as f:
    lat_lon = f.lat_lon

print('lower bound')
print(lat_lon[:, 0].min(), lat_lon[:, 1].min())
print('upper bound')
print(lat_lon[:, 0].max(), lat_lon[:, 1].max())
```

That said, what I would do is just re-raise the error from rex and add some more information, for example:
```
Your request for data with {} interval for {} location is invalid: {rex error}
```

rex raises a custom error: `ResourceValueError` so you can easily catch it with a try/except

**Comment by hivanov-nrel** [comment]
@rpauly18 i think the error given by rex works well at the moment in my opinion. I will make sure to add this check on the matlab side.

**Comment by rpauly18** [comment]
Agreed. Thank you!
