### ISSUE TITLE
requirements - numpy<1.21.0 ?

### ISSUE THREAD

**Issue by fleming79** [MHKiT-Software/MHKiT-Python#133]
I'm using winpython which provides [numpy 1.21.0+mkl](https://github.com/winpython/winpython/blob/master/changelogs/WinPython-64bit-3.9.5.0.md) . After running pip install mhkit causes uninstallation of numpy-mkl which subsequently breaks the the distribution.

Is the requirement numpy<1.21.0 a permanent feature?

Also, is there a reason that relative imports aren't being used between modules?

**Comment by ssolson** [comment]
Please follow #135 as I check the status of numpy versioning.

We tend to use explicit imports as it is more readable and more clear exactly where things are being imported from. If you have some reason you think we should be using relative imports I would be interested to hear it.

Thank you for your interest in MHKiT.

**Comment by ssolson** [comment]
The numpy versioning requirement has been removed.

**Comment by fleming79** [comment]
Thank you for making the change to the requirements. Can you tell me when do you plan to make a new release?

Regarding relative imports, I guess I'm more used to using them in modules, using them guarantees you get the exact module that you're looking for ... I had thought of adding mhkit as a submodule in my own modules so I had a bit more control over the source. But without having mhkit in the path, the submodule imports don't work (an unusual use case).  Changing them to relative, means they work as expected. 

Would you mind re-considering some of the other requirements for mhkit? For example [pecos](https://github.com/sandialabs/pecos/blob/main/requirements.txt) will install [jinja2](https://jinja2docs.readthedocs.io/en/stable/)  which is a web framework and unnecessary for most use cases. For me, I'm just interested in using the pandas/numpy based calculations. 
Perhaps you can just copy the necessary functions directly into the qc module instead of importing from pecos and having it as a requirement?

**Comment by ssolson** [comment]
Hello!

We are always working on MHKiT and releases occur when it makes sense.

You have full control over the source when you pip install -e from your github branch. Like you said this an unusual use case and we do not plan to design our package for it.

We have no plans to remove pecos. Thank you for your suggestion. 

As we have solved the specific Numpy issue and to keep things tidy I am closing this issue. Please feel free to open another issue if have any new issues. Thanks again for your interest in MHKiT.
