### ISSUE TITLE
Spectral bandwidth function

### ISSUE THREAD

**Issue by fleming79** [MHKiT-Software/MHKiT-Python#139]
This function always returns 1 for spectrums that I've passed. Do you have a ref for this function? Perhaps the brackets in the denominator are erroneous?

https://github.com/MHKiT-Software/MHKiT-Python/blob/dd927ba0e6eaaa1e5e829a48be1c62d02b0a25f7/mhkit/wave/resource.py#L503

```
 e = np.sqrt(1- (m2**2)/m0/m4) 
```

**Comment by ssolson** [comment]
Hey fleming! Thank you for your interest in MHKiT. Let me see if we can help you out.

@kmruehl I checked out the MHKiT test and the test is essentailly returning the value of 1 (e.g. in [test_wave](https://github.com/MHKiT-Software/MHKiT-Python/blob/dd927ba0e6eaaa1e5e829a48be1c62d02b0a25f7/mhkit/tests/test_wave.py#L445) calculated is equal to
0.9999999994879673). I am not sure is this is correct or not so I started looking for a reference. I could not find a reference for this equation in any of the IEC standards or in Falnes or in the Wec-Sim documentation although I certaintly could have used the wrong serach terms. 
Could you help me find a reference for the spectral bandwidth equation here so we can confirm everything is working as expected?

**Comment by kmruehl** [comment]
@ssolson I did a quick search and reviewed IEC TC114 62600-101, but cannot find this formula either. It's possible that it's from a textbook, but I do not currently have access to those. However, in my search I found discussion of this parameter, it appears there are many different possible formulas. In short, I think the formula should be revised (ore removed) and a citation added.
