### ISSUE TITLE
NREL-REX incompatible with latest h5py

### ISSUE THREAD

**Issue by ssolson** [MHKiT-Software/MHKiT-Python#144]
h5py has pushed version 3.6.0 which is incompatible with NREL-REX. Therefore MHKiT now requires h5py<=3.5.0

@rpauly18 can you reach out about NREL's plans to update the module? We may need to add a version requirement around h5py but because of the Matlab compatibility issues, this has the potential to exacerbate the h5py issues already being worked on.

**Comment by rpauly18** [comment]
@ssolson my contact on the Rex team no longer works at NREL. They have a prescribed format for submitting issues. Can you submit an issue about this on their git page(https://github.com/NREL/rex/issues) ?

**Comment by ssolson** [comment]
I just reinstall 0.3.6 and ran the wave tests without issue. As I cannot reproduce the issue again I will close this for now.
