### ISSUE TITLE
Finding Alaska Data

### ISSUE THREAD

**Issue by alimayt** [MHKiT-Software/MHKiT-Python#151]
I believe that the mhkit source code for extraction of hindcast data does not search the Alaska region yet (I know that Hindcast data was uploaded to AWS afterward). It seems like the region just needs to be added to the hindcast.py code, but I am not certain what the defining lat and lon are for the region. After failing using mhkit, I was able to extract the Alaska dataset using rex.

**Comment by alimayt** [comment]
@rpauly18 do you have an idea of when it will be available or what kind of quality issues I should be looking for? I noticed a couple of years (1979,1991, and 2010) that seemed to be missing some data (in the case of 1991 the data isn't on AWS at all), and have worked around that, but other than that, all I really have to go off of in terms of "checking the quality" is the metadata and the journal publication from the Hindcast team.  Do you have any further suggestions?

**Comment by rpauly18** [comment]
@alimayt I suggest you reach out to Aidan Bharath at Aidan.bharath@nrel.gov. He works directly on the hindcast data.
