### ISSUE TITLE
Metocean Module

### ISSUE THREAD

**Issue by ssolson** [MHKiT-Software/MHKiT-Python#167]
@rpauly18 do you have suggestions for data or functions beyond pulling in NDBC wind data for our metocean module?

@akeeste and I were discussing what direction to head after PR #152 is merged.

**Comment by akeeste** [comment]
Noting that we also had some discussion on using [Argo buoys](https://argo.ucsd.edu/) to get temperature and salinity over the entire water column. However these buoys drift over time which might pose some difficulties.
