### ISSUE TITLE
Delft3D z calculation 

### ISSUE THREAD

**Issue by browniea** [MHKiT-Software/MHKiT-Python#172]
### Describe the bug:
Add a clear description of what the refence of z is. 

### The issue:
 In the code **[d3d.py](https://github.com/MHKiT-Software/MHKiT-Python/blob/master/mhkit/river/io/d3d.py)** two function output the z location of data points ( `get_layer_data`  and  `get_all_data_points` ).  The refence for this output needs to be clarified whether its the free surface or the zero water level.

**Comment by ssolson** [comment]
Did we switch this to a standard output?

Do we still want to add a new/ custom output?

**Comment by browniea** [comment]
Z is still calculated as "the depth from the zero-water level at the surface" 

`d3d.py` lines 218-227
```
   if dimensions== 2:
        if layer_dim == 'FlowLink_xu FlowLink_yu': 
            z = [bottom_depth_wdim]-water_level_wdim
        else:
            z = [bottom_depth]-water_level
    else:
        if layer_dim == 'FlowLink_xu FlowLink_yu': 
            z = [bottom_depth_wdim*layer_percentages[layer_index]]-water_level_wdim 
        else:
            z = [bottom_depth*layer_percentages[layer_index]]-water_level
```

yes, I think instead of outputting `z` we want to output `depth` and move this to it's own function `depth_zero_water_level`

**Comment by ssolson** [comment]
- No custom z
- no surface reference option in the function
- Output water depth and water level always
- water level is a constant in z direction
- water depth is variable by % of layer
