### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [MHKiT-Software/MHKiT-Python#198]
Hi, In **MHKiT-Python**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
pandas>=1.0.0
numpy>=1.21.0
scipy
matplotlib
requests
pecos>=0.1.9
fatpack
lxml
scikit-learn
NREL-rex>=0.2.63
six>=1.13.0
netCDF4<=1.5.8
xarray
statsmodels
dolfyn>=1.0.0
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **numpy** can be changed to *>=1.8.0,<=1.17.2*.
The version constraint of dependency **matplotlib** can be changed to *>=1.3.0,<=3.0.3*.
The version constraint of dependency **requests** can be changed to *>=0.2.1,<=0.2.3*.
The version constraint of dependency **requests** can be changed to *>=0.7.0,<=2.24.0*.
The version constraint of dependency **requests** can be changed to *==2.26.0*.
The version constraint of dependency **scikit-learn** can be changed to *>=0.13,<=0.21.3*.
The version constraint of dependency **xarray** can be changed to *>=0.18.0,<=2022.6.0rc0*.
The version constraint of dependency **statsmodels** can be changed to *>=0.6.0-rc1,<=0.13.2*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the numpy</summary>
 <pre>numpy.linalg.lstsq
numpy.linalg.det
numpy.ma.masked_outside
numpy.ma.masked_where
numpy.ma.masked_invalid
numpy.ma.getdata
numpy.ma.masked_array
numpy.ma.filled
numpy.linalg.inv
numpy.ma.where
numpy.fft.fft
numpy.linalg.norm
</pre>
</details>
<details><summary>The calling methods from the matplotlib</summary>
 <pre>matplotlib.gridspec.GridSpec
matplotlib.dates.DayLocator
matplotlib.dates.DateFormatter
</pre>
</details>
<details><summary>The calling methods from the requests</summary>
 <pre>requests.get
</pre>
</details>
<details><summary>The calling methods from the scikit-learn</summary>
 <pre>sklearn.decomposition.PCA
sklearn.decomposition.PCA.fit
sklearn.metrics.mean_squared_error
</pre>
</details>
<details><summary>The calling methods from the xarray</summary>
 <pre>xarray.Dataset.to_pandas
xarray.load_dataset
</pre>
</details>
<details><summary>The calling methods from the statsmodels</summary>
 <pre>statsmodels.nonparametric.kde.KDEUnivariate.evaluate
statsmodels.nonparametric.kde.KDEUnivariate.fit
statsmodels.nonparametric.kde.KDEUnivariate
</pre>
</details>
<details><summary>The calling methods from the all methods</summary>
 <pre>pandas.DataFrame.reshape
numpy.outer
time._fill_time_gaps
fit_peaks
base._handle_nan
func2
fd.read_ui32
data.variables.keys
dictionary_of_DataFrames.keys
numpy.asarray.__len__
self._init_data
rc.index
self.pot.cdf
self.ensemble.clean_data
numpy.issubdtype
tdat.epoch2dt64.astype
rotb._check_rotmat_det.all
stdev.append
f.pd.Series.diff
pytz.timezone
region_search
timeindex_end.append
xarray.Dataset
matplotlib.pyplot.semilogx.set_ylim
acceleration.append
self.f.read_ui8
xarray.testing.assert_allclose
date2str
array.astype.astype
energy_period.squeeze
base._handle_nan.pop
_ensemble
P.squeeze.copy.squeeze
rotb._set_coords.get
os.path.abspath
self._calc_lastblock_iswhole
_rotate_inst2head
scipy.interpolate.griddata
request_netCDF
numpy.concatenate
json.loads
mhkit.river.graphics._xy_plot.scatter
wave_number
numpy.linalg.lstsq
numpy.arctan
_Ad2cpReader.read_into
_dates_to_timestamp
matplotlib.pyplot.gca.xaxis.set_major_locator
_performance_matrix
numpy.nonzero
numpy.seterr
lib._headconfig_int2dict
datachunk.std
TI_data_raw.drop
scipy.stats.binned_statistic_2d
meta.reset_index.reset_index
numpy.zeros.reshape
numpy.maximum
YY.ravel
matplotlib.pyplot.setp
counts.copy.squeeze
_gumbel_density
_initialize_polar
year.str.data.loc.copy
self.readnext
id.function_map.get
fig.tight_layout
matplotlib.pyplot.semilogx
fd.read_ui16
zip
self._reopen
lib._alt_status2data
datetime.datetime.strptime
matplotlib.pyplot.semilogx.set_yticklabels
scipy.signal.detrend.dropna
kwargs.get
struct.pack
self.f.read.decode
numpy.atleast_1d
_nans
rotate.base._set_coords.get
bp.twiny.tick_params
scipy.fftpack.fftfreq
hh.copy.copy
f_ebb
V.max
P.squeeze.copy
numpy.ceil
key.df.astype
pandas.DataFrame.from_dict.to_json
epoch2date
newax.spines.set_position
forceAddedMass.append
mcol.A.C.sum
numpy.ma.where
dateFormat.humanTime.datetime.datetime.strptime.timetuple
f.readline.replace
struct.unpack.decode
_xy_plot.legend
ax.errorbar
pDp.set_xlabel
mhkit.wave.performance.capture_length_matrix
months.Hs.groupby.mean
tmp_body.set_index.set_index
_write_constraint_output
line.replace.strip.replace
line.strip.replace.replace
numpy.swapaxes
rotate.vector._euler2orient
matplotlib.pyplot.cm.viridis
_isuniform
numpy.ones_like
numpy.atleast_1d.sort
mhkit.tidal.resource._flood_or_ebb
frequency_bins.squeeze
struct.Struct.unpack
ax.legend
list
_write_body_output
lib._reduce_by_average
ky.alt_status.astype
_read_bin.bin_reader
self.cfg.self.f.read_ui8.np.array.reshape
mhkit.river.graphics._xy_plot.text
_set_coords
matplotlib.pyplot.subplot.twiny
time_all.datetime.datetime.fromtimestamp.astimezone
matplotlib.pyplot.semilogx.set_xlabel
struct.Struct
Hd2.argmax
base._handle_nan.astype
numpy.dtype
_set_rdi_declination
self.f.read_ui16
variable.data.variables.coordinates.str.split
_check_inst2head_rotmat
datachunk.max
_read_block_txt
nm.self.getattr
int.df.len.np.zeros.astype.astype
_xml_to_dataframe
ky.rstrip
f.readline.count
_LinFunc
nm.dv.copy
names.append
pt1.flatten
variable.data.get_dims
out.astype.astype
ds.assign_coords.astype
tmlib.epoch2dt64
max
matplotlib.pyplot.semilogx.get_ylim
pandas.to_numeric
mhkit.qc.check_timestamp
numpy.log10
numpy.array
buoy_id_year_str.str.split.rename
pt2.flatten
scipy.stats.lognorm.cdf
available_data.append.append
scipy.signal.convolve2d
lib._beams_cy_int2dict
func
pandas.to_datetime.append
method.copula_functions
_reorg
struct.unpack
buoyname.data.tostring.decode
self._read_str
_Ad2cpReader.readfile
ds.coord_sys.lower
scipy.io.loadmat.keys
numpy.atleast_1d.diff
Hs_months.boxplot.get_xlim
self._sci_func.append
bin_stat_list.append
nc.variables.compressed
types.index
xarray.Dataset.to_pandas
self.init_data
_date_string_to_datetime.drop
get_netcdf_variables.keys
eta.keys
ep_time.item.astype
_RdiReader
global_peaks
datetime.timedelta.toordinal
numpy.unique
rex_waves.get_lat_lon_df.to_xarray
t.replace
_check_file_ext
spec.multiply
numpy.array.mean
arr_shape.np.asarray.take
vd.sci_func
self._cfgnames.get
numpy.round
matplotlib.pyplot.plot
re.split
va._empty_array
data.pop
df_datetime.set_index.drop
self.mean
scipy.stats.exponweib.ppf
arr.copy.copy
da.extend
self.cs.add
lib.get_index
ds.inst_model.lower
json.load.pop
scipy.interpolate.interpn.argsort
numpy.trapz
numpy.ma.getdata
numpy.nanmax
datachunk.isnull
numpy.reshape
wave.squeeze.append
slice
numpy.argmax
sklearn.metrics.mean_squared_error
copy.copy.append
IOError
line.get_xydata
base._get_filetype
mhkit.river.graphics._xy_plot.set_yticklabels
int
numpy.random.normal
Hs_months.boxplot.grid
matplotlib.pyplot.semilogx.autoscale
buoys.id.str.len.copy
self.tell
pandas.plotting.register_matplotlib_converters
ky.out.append
numpy.iscomplexobj
matplotlib.pylab.setp
scipy.stats.lognorm.ppf
zlib.decompress.copy
swan_file.split.lower
callable
dataset.attrs.keys
_in_group
vector._euler2orient
matplotlib.pyplot.semilogx.set_ylabel
directions.keys
dv.copy
abs
pandas.DataFrame.compressed
x2_bin.mean
fig.savefig
self._cs_struct.unpack
runLines.extend
pandas.read_html
open.seek
dict
numpy.eye
_get
newax.xaxis.set_ticks_position
XX.ravel
elm.split
wave.squeeze
Hs.index.month_name
std.append
forceConstraint.append
matplotlib.pyplot.grid
self.f.read_i16
data_raw.to_xarray.rename
short_term_extreme
self.read_cfg
mhkit.dolfyn.io.api.save_mat
numpy.transpose.append
_check_index
re.search.group
f.readline.startswith
Hd1.argmax
dt642epoch
self.close
matplotlib.pyplot.subplot.grid
numpy.dot
numpy.hstack
response.text.pd.read_html.Name.dropna
numpy.polyval
datetime.timezone.utc.t.replace.timestamp
forceMooring.append
matplotlib.pyplot.gca.xaxis.set_major_formatter
numpy.sqrt
collections.defaultdict.copy
netCDF4.Dataset
harmonics.sort_index.reindex
omat.rename.assign_coords
self._read_hdr
wave_celerity
warnings.simplefilter
_xy_plot.set_ylabel
lib._status2data
datetime.datetime.fromordinal
table.rename.sort_values
lib._reduce_by_average_angle
mhkit.dolfyn.io.api.save
_variable_setlist
self._format.append
setuptools.find_packages
V.squeeze.copy
ax.set_title
pHs.tick_params
re.sub
rotate.base._set_coords
_xy_plot
hasattr
base._find_userdata
self.finalize
get_all_data_points
S.keys
dat.attrs.pop
bin_mean.isna.any
pandas.DataFrame.from_dict.append
ds.attrs.pop
len
pHs.twinx.set_ylim
energy_period
data.unstack.reset_index
self._read_filehead_config_string
sklearn.decomposition.PCA.fit
time.dt642date
pHs.twinx.set_ylabel
ens_stop.ens_start.np.arange.astype
classification.append
block_to_table
pandas.DataFrame.sort_values
scipy.stats.invgauss.cdf
df_datetime.columns.astype
scipy.spatial.transform.Rotation.from_quat.as_matrix
numpy.einsum.copy
_xy_plot.set_xlabel
self.f.read_float
polynomial_coefficients
matplotlib.pyplot.subplot.annotate
t.pd.Series.diff
ax.grid
rotate.api.set_inst2head_rotmat
sCg.dCg.pd.concat.sort_index
scipy.stats.median_abs_deviation
bp2.axes.get_yaxis
matplotlib.pyplot.title
get_index.copy
dv.pop
fatpack.find_rainflow_ranges
ValueError
pTp.plot
_read_block_mat
scipy.stats.gumbel_r.fit
open.close
numpy.binary_repr
self._shape.append
pandas.read_csv
harmonics.sort_index.sort_index
mhkit.wave.resource.significant_wave_height
f_total
numpy.einsum
numpy.digitize
self.remove_end
self.read_hdrseg
mhkit.dolfyn.time.dt642epoch
V.min
Hs_months.boxplot.set_ylabel
math.ceil
numpy.tanh
sorted
setuptools.setup
sys.exit
_BitIndexer
numpy.ma.masked_outside
scipy.stats.binned_statistic
numpy.sum
matplotlib.pyplot.semilogx.text
self._names.append
delta.datetime.timedelta.i.begin.strftime
self.print_progress
numpy.transpose
fd.read_i32
numpy.zeros_like
mhkit.river.graphics._xy_plot
self.peaks.cdf
forceLinearDamping.append
forceActuation.append
rex_waves.get_lat_lon_df
r_vec._rotate_inst2head
_setd
significant_wave_height
statsmodels.nonparametric.kde.KDEUnivariate.fit
data.index.round
month.cumSum.sort_values
i2.inds.gd.a.ii.__len__.ii.__len__.np.arange.i2.inds.i2.inds.gd.a.np.diff.astype
matplotlib.pyplot.legend
rfnm
mhkit.river.resource.exceedance_probability.sort_values
TI_data.drop.drop
blockmaxima_methods.keys
matplotlib.pyplot.suptitle
numpy.product
scipy.stats.norm.pdf
pandas.DataFrame.isna
sklearn.decomposition.PCA
tmlib.timedelta
float
xtickDegrees.index
pDp.set_ylabel
numpy.abs.sum
_ShortTermExtreme
numpy.fromfile
datetime.datetime.um.index.total_seconds
omat.rename.rename
self.rd_time
include_params.difference.intersection
pp.copy.copy
obj.keys
xarray.load_dataset
lib._calc_time
numpy.array.argmax
mhkit.river.graphics._xy_plot.bar
matplotlib.pylab.gca
matplotlib.dates.DayLocator
peaks_methods.keys
buoy_id_year_str.str.split
io.BytesIO
rex.MultiYearWaveX
line.rstrip.strip
numpy.zeros.sum
V.squeeze.copy.to_frame
numpy.max
numpy.random.seed
datachunk.isnull.any.any
scipy.stats.norm.fit
harmonics_sq.sum
self.findnext
time.date2dt64
matplotlib.pyplot.gca
defs._nans
timeindex_start.append
_xy_plot.set_title
numpy.allclose
D.squeeze.copy.squeeze
list.remove
swan_file.split
fd.read_i16
df.set_index.apply
f.readline.rstrip.split
scipy.io.loadmat.pop
mhkit.dolfyn.io.api.load_mat
NotImplementedError
tdat.np.isnan.any
ds.attrs.keys
self.f.read_ui16.remove
re.sub.split
RuntimeError
edges.min
dict.fromkeys
lib._boolarray_firstensemble_ping
scipy.stats.lognorm.pdf
ky.split
matplotlib.pyplot.subplot.scatter
X.pd.Series.describe
ax.plot
types.count
getattr
numpy.float_.axis.sz.np.arange.reshape
unwrap_vector
base._create_dataset
self.init_data.keys
rotate.vector._calc_omat
list.index
numpy.empty_like
var.nc.variables.compressed
mhkit.dolfyn.time.epoch2dt64
sorted.remove
mhkit.wave.performance.capture_length
forceRestoring.append
numpy.min
numpy.array.from_quat
_principal_component_analysis
_nonparametric_copula_parameters
rdr.dat2sci
function_map.get
out_frame.lower
func_name.self.getattr
numpy.abs
bp.twiny.set_xticks
numpy.array.fd.read_ui8.sum
line.strip.re.split.join.split
pTp.set_ylim
matplotlib.gridspec.GridSpec
D.min
numpy.around
scipy.stats.exponweib.fit
read
self._init_burst_readers
numpy.nan_to_num
numpy.deg2rad
_recatenate
data.Te.max
counts.copy
scipy.optimize.fsolve
mhkit.wave.resource.frequency_moment
set
matplotlib.pyplot.semilogx.set_xlim
id.config.update
ky.status0_data.astype
fname.rsplit
matplotlib.pyplot.subplot.boxplot
numpy.mean.insert
pandas.concat
self._get_out_type
data.Hm0.max
include_params.difference.difference
bool
self.f.read
_DataDef
self._advance_ens_count
xarray.DataArray
numpy.arange
delta_f.S.multiply.multiply.sum
matplotlib.pyplot.semilogx.set_yscale
open
pandas.DataFrame.idxmax
metaData.set_index.T.to_dict.pop
list.append
fobj.read
numpy.mean.append
matplotlib.pyplot.contour
pandas.DataFrame.iterrows
matplotlib.pyplot.imshow
path.replace
self.config.upper
os.path.isfile
rotate.api.set_declination
vector_statistics
significant_wave_height.squeeze
region_selection
_normalize_angle
datetime.datetime
Exception
Hs.to_frame.groupby
numpy.split
dat.split
os.path.dirname
wave_length
polynomial_coeff
numpy.ones
pandas.DataFrame
pHs.grid
self.shape
ky.self._burst_readers.init_data
j.year_data.ybins.i.year_data.xbins.year_data.J.sum
bl.astype
self.checkheader
self.f.tell
ax.set_xlabel
data.index.year.unique
P.to_frame.to_frame
i.time.replace
self.checksum
ds.assign_coords.drop_vars
r_vec._check_inst2head_rotmat
F.to_frame.to_frame
_nonparametric_component
matplotlib.pyplot.close
number_of_short_term_peaks
dt.replace.replace
scipy.io.loadmat
_beams_cy_int2dict
tmp_idx.rdr._shape.append
block_maxima
pandas.DataFrame.append
self.read_cfgseg
_write_mooring_output
numpy.all
datachunk.isnull.any
print
numpy.angle
rdr.read
numpy.std
matplotlib.pyplot.subplots
D.squeeze.copy.rank
_parse_filenames
lib._collapse
input
self.init_data.pop
numpy.empty.append
scipy.signal.medfilt2d.flatten
numpy.uint16
_read_userdata
mhkit.tidal.resource._histogram
quaternions.type
ds.assign_coords.to_netcdf
tmp_moordyn.set_index.set_index
mhkit.wave.graphics.plot_matrix
self.read_dat
get_index
open.read
dataset.attrs.pop
collections.OrderedDict.startswith
ep_time.astype.np.array.astype
hex
numpy.ma.filled
time.datetime
fd.tell
self.init_data.update
pandas.Index.get_loc
tmp.self.endian.unpack.np.array.reshape
os.path.normpath
matplotlib.pyplot.colorbar
vardict.items
os.path.expanduser
year_string.df.str.startswith
self.search_buffer
x.strip
pDp.scatter
x1_components.argsort
s.c.stats.exponweib.cdf
self.code_spacing
_Ad2cpReader.sci_data
datachunk.min
numpy.zeros
scipy.stats.rv_histogram
format
name.append
open.readline
TI_data_raw.drop.copy
counts.copy.reshape
monthlengths.append
var.startswith
ln.split
numpy.ma.masked_where
defs.header.read2dict
tmp_constraint.set_index.set_index
self.read.decode
self.init_data.append
_pop
scipy.stats.genextreme
self.print_pos
matplotlib.pyplot.semilogx.set_yticks
df.columns.values.tolist
numpy.sort
i2.inds.gd.a.ti.i2.inds.i2.inds.gd.a.np.diff.astype
vals.count
matplotlib.pyplot.xlabel
numpy.vstack
matplotlib.pyplot.figure
matplotlib.pyplot.subplot.tick_params
matplotlib.pyplot.tight_layout
scipy.stats.linregress
Hs_months.boxplot.set_xticklabels
scipy.signal.hilbert
subset.squeeze.squeeze
numpy.size
forceTotal.append
_rotate_inst2head.copy
_int2binarray
_make_model
itm.split
f.readline.rstrip.split.startswith
matplotlib.pylab.figure
super.__init__
variable2D.compressed.reshape
tools.misc._nans_like
fillgaps
pandas.to_timedelta
matplotlib.pyplot.subplot.set_ylabel
datachunk.mean
fn.spec.multiply.multiply
mhkit.wave.performance.mean_annual_energy_production_matrix
df.len.np.zeros.astype
ratio.g.h.k.wave_celerity.squeeze
str
Hs.to_frame.groupby.boxplot
self.read_hdr
scipy.stats.genpareto.fit
numpy.ones.ravel
f_flood
variable2D.compressed.reshape.compressed
mhkit.river.graphics._xy_plot.stackplot
numpy.poly1d
ds.time.epoch2dt64.astype
adcpo.coord_sys.lower
get_netcdf_variables
_remove_gps_duplicates
P.squeeze.copy.to_frame
_parse_filenames.unique
buoys.id.str.len
tools.misc.interpgaps
TypeError
dt.np.array.astype
ky.self._burst_readers.data_units
rex.WaveX
Hs_months.boxplot.twiny
bp2.axes.get_xaxis.set_visible
datetime.datetime.utcfromtimestamp
self.read_id
rdr._names.index
matplotlib.pyplot.clf
P.to_frame.sum
matplotlib.pyplot.subplot
collections.defaultdict
locals
EOFError
zlib.decompress.replace
H180.argmax
numpy.float32
scipy.stats.kendalltau
mhkit.river.graphics._xy_plot.set_xticks
dict.update
mhkit.utils.unorm
powerInternalMechanics.append
value.array.np.abs.argmin
_get_size
scipy.stats.invgauss.ppf
self._inst.self.getattr
_LongTermExtreme
dict.fromkeys.update
_reduce
depth_regime
_create_index
pandas.Series.squeeze
D.squeeze.copy
requests.get
os.path.getsize
key.rsplit
numpy.asarray
numpy.meshgrid
mler_ts.rename.rename
forceRadiationDamping.append
datetime.datetime.fromtimestamp
_princomp_inv
temp_data.rename.rename
numpy.append
self.f.seek
base._handle_nan.update
numpy.sinh
bin_std_list.append
path.replace.rsplit
dtype.startswith
si
numpy.linalg.det
rr.copy.copy
numpy.arctan2
_crop_data
self.f.read_f64
numpy.logspace
numpy.fft.fft
rotb._check_rotmat_det
_parse_line_metadata.split
ky.startswith
tools.misc._nans
ens_stop.self._index.ens_start.self._index.self._index.sum
Lines.set_index.set_index
line.replace.strip
velocity.append
_check_file_ext.rsplit
numpy.isreal
_remove_gps_duplicates.append
mask.variable.np.ma.masked_array.astype
bp.twiny.set_xticklabels
numpy.sqrt.multiply
filename.rsplit
matplotlib.pyplot.bar
numpy.argsort
delta_f.S.multiply.multiply
numpy.amin
numpy.median
numpy.polyfit
bisect.insort
mhkit.dolfyn.io.api.load
pDp.set_ylim
_getbit
lib._status2data.pop
wave_output.set_index.set_index
quaternions.isel
numpy.concatenate.max
data.unstack
numpy.tan
pandas.Index
f.read
J.index.month.unique
numpy.column_stack
ste_i.cdf
ds.attrs.ds.attrs.format.lower
slice1d_along_axis
defs._format
_read_usgs_json
_euler2orient
edges.max
scipy.io.savemat
buoyname.data.tostring
base._set_coords
defs._calc_burst_struct
metaData.set_index.T.to_dict
rotate.rdi._calc_beam_orientmat
self._units.append
matplotlib.pyplot.semilogx.set_xticklabels
mhkit.river.graphics._xy_plot.set_theta_direction
self.config.pop
frequency_bins.S.frequency_moment.squeeze
V.squeeze.copy.squeeze
pandas.DataFrame.from_dict
ldr.load_data
col.startswith
_remove_gps_duplicates.pop
fd.read_i8
table.rename.rename
defs._calc_bt_struct
pytz.timezone.end_datetime.astimezone.timestamp
status0_key.replace
mhkit.river.graphics._xy_plot.set_xticklabels
defs._calc_echo_struct
self.findnextid
pytz.timezone.time.pd.to_datetime.astimezone.timestamp
self.f.close
_VarAtts
_find.__len__
Hm0.values.max
to_timestamp
numpy.nanmean
self.f.read.splitlines
isinstance
setattr
_format
numpy.isnan
fatpack.find_range_count
numpy.prod
time.pd.to_datetime.astimezone
self.read_hw_cfg
numpy.ma.masked_array
line.rstrip.strip.lstrip
self.check_offset
da.pop
numpy.mean
matplotlib.pyplot.xscale
box_data.append
p
bp2.axes.get_yaxis.set_visible
velocities.max
pandas.DataFrame.rename
numpy.concatenate.argsort
numpy.concatenate.mean
Hs_months.boxplot.tick_params
numpy.floor
f.readline.strip
idx.copy.max
round
self.cfg.self.f.read_i16.np.array.reshape
position.append
scipy.optimize.curve_fit
lib._status02data
filenames.str.contains
df.set_index.set_index
pHs.twinx
l.squeeze.squeeze
ep_time.item.item
numpy.tile
str.key.df.astype.str.zfill
pDp.grid
ax.set_ylabel
mhkit.wave.resource.energy_flux
mhkit.river.graphics._xy_plot.set_theta_zero_location
cols.data.apply
advo.inst_model.lower
base._abspath
collections.OrderedDict
collections.OrderedDict.items
numpy.diff
scipy.signal.detrend
scipy.stats.exponweib
adcpo.inst_make.lower
rotb._beam2inst
_idata
super
open.write
tmlib.datetime
df.columns.values.tolist.index
pandas.DataFrame.set_index
moorDyn_output.update
all
ky.lstrip
data.index.duplicated
os.path.relpath
pandas.to_datetime
Hs_months.boxplot.annotate
numpy.sin
getUnixTimestamp
reglist.count
pandas.DataFrame.from_records
var.metaData.vars.metaData.cols.values.tolist
x.to_numpy.to_numpy
min
_supported_params
available_data.year.str.strip
_calc_omat
_xy_plot.grid
numpy.linalg.inv
ds_dict.pop
pHs.set_ylabel
pHs.plot
scipy.signal.welch
mhkit.wave.resource.energy_period
nc.variables.compressed.tobytes.decode
matplotlib.pyplot.yticks
type
dat.copy
warnings.warn
ds.assign_coords.assign_coords
matplotlib.pyplot.show
matplotlib.pyplot.axes
matplotlib.pyplot.semilogx.set_xticks
zlib.decompress
id.config.pop
copy.copy
numpy.linspace
DELs.sum
cfh.split
fit_maxima
numpy.histogram2d
line.strip.split
datetime.date
numpy.array.append
numpy.empty
numpy.sign
rotb._set_coords
mhkit.wave.performance.wave_energy_flux_matrix
sum
numpy.shape
_validate_date.astimezone
_parse_line_metadata
reglist.append
year_data.J.sum
interpgaps
dnow.astype
advo.coord_sys.lower
numpy.histogram
_find
self._struct.unpack
matplotlib.dates.DateFormatter
df.set_index.drop_duplicates
matplotlib.pyplot.colorbar.set_label
units.lower
scipy.interpolate.interp1d
numpy.multiply
include_params.difference.add
elm.remove
numpy.arcsin
x1_bin.mean
obj.items
bin_mean.isna.any.any
scipy.stats.norm.ppf
numpy.ma.masked_invalid
self._config.items
pHs.set_ylim
numpy.cos
matplotlib.pyplot.rcParams.update
months.Hs.groupby.count
fd.read_ui8
data.dtypes.eq
os.path.join
numpy.linalg.norm
numpy.array.squeeze
frequency_moment
numpy.any
str.LM.to_pandas
ky.status_data.astype
pytz.timezone.start_datetime.astimezone.timestamp
dnow.dnow.astype
Hs.index.month_name.unique
out.view.view
statsmodels.nonparametric.kde.KDEUnivariate
matplotlib.pyplot.semilogx.set_xscale
self.f.reads
nc.variables.compressed.tobytes
df_datetime.set_index.set_index
scipy.interpolate.interpn
datetime.timedelta
matplotlib.pyplot.semilogx.plot
phases.squeeze
tmp.partition.decode
Hs_months.boxplot.set_title
numpy.random.rand
numpy.isclose
numpy.rollaxis
self._sci_data
data.variables.coordinates.str.split
_read_usgs_json.combine_first
open.tell
self.read_buffer
d.np.asarray.reshape
any
_Ad2cpReader
_calc_orientmat
grp.dat.pop
D.max
base._make_model
ky.endswith
join
matplotlib.pyplot.subplot.set_xticklabels
dt64.astype
kwargs.pop
numpy.nansum
_date_string_to_datetime
tools.misc.fillgaps
scipy.stats.invgauss.fit
column.df.apply
_std_ddof1
data.extend
xml.etree.ElementTree.fromstring
orientation_down.astype
matplotlib.pyplot.semilogx.imshow
idx.copy.astype
key.ds.rename
set.difference
json.dump
get_layer_data
forceExcitation.append
self._N.append
dat.coord_sys.lower
numpy.zeros.put
pandas.DataFrame.sum
data_list.append
tmp_pto.set_index.set_index
_Peaks
dt64.astype.astype
defs.Struct
self.read_nocode
numpy.exp
matplotlib.pyplot.semilogx.get_xlim
matplotlib.pyplot.semilogx.legend
i.stdev.loc.std
rdr.read.hex
mler.fillna.fillna
numpy.array.max
velocities.min
data_key.endswith
time._fullyear
filenames.str.split
rotate.rdi._calc_orientmat
Hs.index.date
numpy.nan_to_num.astype
_bcd2char
scipy.signal.medfilt2d
pandas.Series
_generate_sample_data
numpy.random.random_sample
cfg_u.astype
numpy.moveaxis
blocksize_count.argmax
scipy.stats.norm.cdf
self.f.read_ui16.index
um.to_frame.to_frame
matplotlib.pyplot.subplot.set_title
forceInternalMechanics.append
Hs.to_frame
_copula_parameters
lat_lon.lat_lon.items
pTp.grid
scipy.stats.gumbel_r
matplotlib.pyplot.ylim
Te.values.max
json.load
rotate2
line.strip.replace
_iso_prob_and_quantile
data_defs.keys
range
numpy.arange.__len__
struct.unpack.partition
numpy.where
metaData.set_index.T.to_dict.set_index
_NortekReader
self.f.read_ui16.insert
pDp.xaxis.get_majorticklabels
matplotlib.pyplot.ylabel
pandas.DataFrame.squeeze
self._read_burst
_validate_date
rdr.readfile
tuple
self.read_head_cfg
scipy.optimize.minimize
_headconfig_int2dict
date_list.append
_write_pto_output
bp.twiny.set_xlim
f.readline.rstrip
pTp.set_ylabel
tmlib.date2epoch
data_key.year_data.keys
dky.startswith
dates_to_datetime
find_nearest
r_vec._rotate_inst2head.get
self.read_user_cfg
scipy.stats.genpareto
numpy.unwrap
re.search
numpy.rad2deg
self.read
struct.calcsize
ste_peaks
numpy.split.append
ds.attrs.append
scipy.stats.rv_histogram.pdf
numpy.ma.masked_outside.compressed
numpy.ravel
matplotlib.pylab.savefig
numpy.power
x2_bin.std
Hs.groupby
scipy.stats.genextreme.fit
pandas.DataFrame.multiply
forceMorrisonAndViscous.append
time.epoch2dt64
bp2.axes.get_xaxis
fd.seek
lib._calc_config
newax.xaxis.set_label_position
numpy.log
numpy.amax
t.strftime
statsmodels.nonparametric.kde.KDEUnivariate.evaluate
numpy.cumsum
matplotlib.pyplot.text
r_vec._rotate_inst2head.copy
obj.type
time.date2epoch
numpy.argmin
key.ds.assign_coords
_parse_line_metadata.endswith
time.mktime
_xy_plot.plot
self._check_nortek
set.intersection
mhkit.river.resource.exceedance_probability
pandas.Series.between
enumerate
df.set_index.append
tmp_mooring.set_index.set_index
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by ssolson** [comment]
Thank you for your interest in MHKiT. We currently find the dependency versioning of MHKiT sufficient and are working on improvements actively through our CI and testing efforts. If you have a specific issue please open a new issue. Thank you!
