### ISSUE TITLE
Turbulence Functions

### ISSUE THREAD

**Issue by browniea** [MHKiT-Software/MHKiT-Python#227]
Adding turbulence calculation examples to MHKiT example ipython notebooks.  

Currently DOLfYN has these built in functions for calculating turbulence: [Dolfyn Binning Tools](https://dolfyn.readthedocs.io/en/latest/apidoc/dolfyn.binners.html).  Most of these functions are designed with an ADV in mind but would work for a single depth bin of ADCP data. 

Turbulence Variables to include in Dolfyn, d3d, River, and Tidal modules: 
- Turbulence Intensity 
- Turbulent Kinetic energy 

Turbulence variables to consider: 
- Renolds stress 
- Energy Spectrum 
- Coherence spectrum 
- Length scale

**Comment by jmcvey3** [comment]
@browniea I'm meeting with Levi Kilcher tomorrow to discuss the PR branch I shared with you. The goal is to work through scientifically-related concerns and get that published.
