### ISSUE TITLE
Allow newer `xarray` versions?

### ISSUE THREAD

**Issue by cmichelenstrofer** [MHKiT-Software/MHKiT-Python#228]
Currently MHKiT requires `xarray<=2022.9.0`. I want to use MHKiT together with `capytaine` which uses capabilities in newer versions of `xarray`. Could the upper limit on xarray be removed?

**Comment by akeeste** [comment]
@cmichelenstrofer I don't know the reason for the version limitation off-hand, but will look into this next week.

Adam

**Comment by ssolson** [comment]
#240

**Comment by ssolson** [comment]
Fixed in #240
