### ISSUE TITLE
Assert Statements are for Debugging

### ISSUE THREAD

**Issue by ssolson** [MHKiT-Software/MHKiT-Python#242]
Currently MHKiT uses assert staements in its production code (primarilty for type checking functional inputs). As stated in the docs (https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement) assert stements are for debugging. 

We should raise an error if the user does not pass the correct information. 

So going forward we would convert:
```python
assert isinstance(station_number, (str, type(None))), (f'station_number must be  of type string')
```
to this

```python
if not isinstance(station_number, (str, type(None))):
    raise ValueError(f'station_number must be of type string. Got: {station_number}')
```

**Comment by ssolson** [comment]
Here is an article covering this idea in more detail:
https://snyk.io/blog/the-dangers-of-assert-in-python/

![image](https://github.com/MHKiT-Software/MHKiT-Python/assets/13438942/8affe511-ab42-4a41-8316-65e1a5dc36f9)

**Comment by onedeeper** [comment]
Hello! I'm trying to get my feet wet with some python open source. This seems straight forward so I'm happy to take care of it. Does this seem like a good first issue? Thanks!
