### ISSUE TITLE
Power Module 

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-Python#25]
The power module for MHKiT will include functions for computing various types of power from time series of current and voltage (reactive, active, RMS, etc.), harmonics, and flicker. The latter two are used for power quality assessments and are described in IEC TS 62600-30. The rationale for creating a “power” module as opposed to a “quality” module are because there are many power computations that are not specific to power quality testing, but still need a home. We initially had some power computations in the wave.resource module, but I believe pulling them out into a power module makes more sense since they are not device type specific. Also, having a module called “quality”, following the single word naming convention adopted by MHKiT, may also be ambiguous to users. 

The power module is proposed to have two submodules: 
1)	Characteristics
2)	quality

The characteristics submodule will feature functions for calculating RMS, active, reactive, etc. values of current, voltage, and power. As such, I propose that we move the dc_power and ac_power_three_phase functions out of wave.performance into this submodule. 

The quality submodule will contain functions for computing the harmonics of voltage and current, their distortions, and flicker (IEC TS 62600-30). 

The tests for this module will be written using data computed from Labview power quality functions which have been verified for use in accredited wind power quality assessments. Assuming I get permission for this dataset to be made public, these tests will be used for CI as well as examples. If no open dataset is available, synthetic datasets can be created for tests and examples.  

I welcome feedback about this proposed organization for this module.

**Comment by ssolson** [comment]
@rpauly18 can we close this?
