### ISSUE TITLE
Loads Module 

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-Python#27]
Organization:
	There will be a loads submodule added to the wave, tidal, and river modules. Any functions that apply to multiple type of devices will be called upon across submodules like the repeated functions within the river and tidal device modules. Additionally, some utility functions are planned for data format conversions and statistic generations. These will be used across multiple functions. They can be included in the utils module so that other MHKiT modules can make use of them. 

Loads Content: 
	The initial loads content will include functions to compute standard loads quantities from the soon to be approved IEC 62600-3 TS. Any function that is design type specific will clearly state the applicable design (i.e. blade connected to rotor shaft) in the header description. Functions will be included for loads statistics, fatigue analysis, sea trend detection, and visualizations. The visualization functions will be included in the graphics submodules. 

Development workflow: 
	Primary development will be done on @hivanov-nrel MHKiT-Python fork. When the code is ready and stable, a pull request will be submitted to integrate the new module with the main MHKiT-Python repo. 

Tests: 
	This code will be tested initially using loads data collected from wind turbines, since MRE measurements are not currently available. When MRE loads data become available, tests will be modified to use the new loads data. If data is not available for any functions, data will be created to test their functionality. 

Please provide any feedback on this proposed loads submodules.

**Comment by ssolson** [comment]
Closed by #51
