### ISSUE TITLE
Dolfyn Reading Online Singature Deploment Measurments 

### ISSUE THREAD

**Issue by browniea** [MHKiT-Software/MHKiT-Python#286]
Using the Nortek "Signature Deployment" software the online measurement output (.AD2CP files)  have errors being read by `dolfyn.read`

note: Using the same process but a deployment vs online measurement has worked with no issues so far.

**Comment by jmcvey3** [comment]
Was able to fix one of the files so far in https://github.com/jmcvey3/MHKiT-Python/tree/online, the one ending in "0943". The file ending in "4835" also already runs successfully.

**Comment by jmcvey3** [comment]
@browniea Found a way to skip past the header data. See if that works for you
