### ISSUE TITLE
DOLfYN range issue 

### ISSUE THREAD

**Issue by browniea** [MHKiT-Software/MHKiT-Python#291]
When importing data from the Teledyne River Pro ADCP the range of depth bins doesn't load the complete list. the first 'range' screenshot is what DOLfYN imports (before being properly offset for deployment depth). The second screenshot is the correct bin depths in rows of time steps.  

![unnamed](https://github.com/MHKiT-Software/MHKiT-Python/assets/63879572/c4f1f610-fad8-4a38-a548-1a399856e60f)
![unnamed](https://github.com/MHKiT-Software/MHKiT-Python/assets/63879572/c22037d6-bb8b-46fd-b3ec-4e653e9751f9)

**Comment by jmcvey3** [comment]
One more fix for this in #294
