### ISSUE TITLE
Reading ad2cp-file with dolfyn.read gives completely wrong temperature values

### ISSUE THREAD

**Issue by stinawahlgren** [MHKiT-Software/MHKiT-Python#298]
I'm using MHKiT (version 0.7.0) to open an ad2cp-file from Nortek Signature1000 in python, and noticed that the temperature values are completely off. They range between 653.42 and 653.58. Temperature values are normal when I convert the ad2cp-file to a mat-file using Nortek's own software.

Happy to provide more details if needed. Thank you for an overall great software!

**Comment by ssolson** [comment]
Hey @stinawahlgren thank you for your interest in MHKiT and bringing this to our attention.

Is there anyway you could provide us with a the data or a subset of the data that we can use to reproduce this issue?

**Comment by jmcvey3** [comment]
Ah, the water temperature is below 0, isn't it?

**Comment by stinawahlgren** [comment]
> Ah, the water temperature is below 0, isn't it?

Yes, that is correct. Life of a polar scientist :)

**Comment by ssolson** [comment]
@stinawahlgren could you pull PR #299  (`jmcvey3` branch `temp_fix`) and let us know if that resolves your issue?

**Comment by stinawahlgren** [comment]
> @stinawahlgren could you pull PR #299 (`jmcvey3` branch `temp_fix`) and let us know if that resolves your issue?

Yep, this resolves my issue, temperatures are now correct.

Thank you for such a quick handling of the issue!

**Comment by ssolson** [comment]
Thank you for helping us improve the software! Please let us know is you run into any future issues and good luck in your research.
