### ISSUE TITLE
Numpy and Scipy dependencies

### ISSUE THREAD

**Issue by browniea** [MHKiT-Software/MHKiT-Python#334]
The latest versions of Numpy 2.0.0 and SciPy 1.14 gave errors when doing a fresh install.  @Lydia-marine 
Numpy 1.26.2 and Scipy 1.11.3 worked

**Comment by ssolson** [comment]
PR #333 is open address:

For now you need to pin:
numpy <2.0.0
scipy < 1.14.0

**Comment by jmcvey3** [comment]
Gotta love end of Q2 releases

**Comment by ssolson** [comment]
Fixed by #337 and MHKiT v0.8.1 release
