### ISSUE TITLE
Error when computing a 10 year contour for dataset

### ISSUE THREAD

**Issue by jtgrasb** [MHKiT-Software/MHKiT-Python#342]
### Describe the bug:
I am working with a specific dataset and trying to plot the environmental contours for various time periods (including a 10 year period). When I try a 10 year environmental contour, I get the following error. The `environmental_contours()` function works fine with other files and it works fine with other return periods, but it does not work with a 10 year return period for this specific dataset.

### To Reproduce:
Run the following contour_issue.py script to get the error. 

**Minimal working example:** 
[contour_issue.zip](https://github.com/user-attachments/files/16284713/contour_issue.zip)

### Expected behavior:
Should successfully compute the copula for the 10 year period.

### Screenshots:
<img width="424" alt="image" src="https://github.com/user-attachments/assets/02af4e1c-ea80-415e-a024-941cb89f09f6">

### Desktop (please complete the following information):
 - OS: Windows 11
 - MHKiT Version: 0.7.0

**Comment by jtgrasb** [comment]
Thank you for the suggestion. I just updated to 0.8.1, but I am still getting the same error. Here are the versions of other packages that my environment has:
pandas: 2.0.3
numpy: 1.24.4
scipy: 1.10.1

**Comment by ssolson** [comment]
What are your scikitlearn and statsmodel versions?

**Comment by jtgrasb** [comment]
scikit-learn: 1.3.2
xarray: 2022.11.0
statsmodels: 0.14.0

**Comment by ssolson** [comment]
What version of python are you using?

**Comment by jtgrasb** [comment]
python version 3.8.16

**Comment by ssolson** [comment]
Okay. In development we only support 3.10 currently and we will be deprecating 3.8 support in the coming months. Your setup is working for me in 3.11. 

Let me see if I can recreate your issue in 3.8

**Comment by ssolson** [comment]
Okay I was able to recreate your issue on a clean python 3.8 install.

Since you can upgrade to 3.11 I expect this to fix your issue. 

Additionally since we are dropping 3.8 support in the next release of MHKiT I will not fix this issue.

Please let me know if 3.11 works for you.

**Comment by jtgrasb** [comment]
3.11 works for me. Thank you for looking into this!
