### ISSUE TITLE
Error from api.clean.find_surface_from_P(ds, salinity=XX)

### ISSUE THREAD

**Issue by calumkenny** [MHKiT-Software/MHKiT-Python#353]
### Describe the bug:

Error experienced when running api.clean.find_surface_from_P(ds, salinity=XX) function:

> AttributeError: 'NoneType' object has no attribute 'pressure'

### To Reproduce:
Use function on RDI ADCP without pressure variable.

### Expected behavior:
Error occurs.

### Additional context:
Working session with @jmcvey3.

**Comment by akeeste** [comment]
Resolved with #354
