### ISSUE TITLE
PacWave clusters plot has flipped axes labels

### ISSUE THREAD

**Issue by jtgrasb** [MHKiT-Software/MHKiT-Python#355]
### Describe the bug:
In the PacWave resource characterization example, the axes labels on the sea state representative clusters plot are flipped. 

### To Reproduce:
[PacWave Resource Characterization](https://mhkit-software.github.io/MHKiT/PacWave_resource_characterization_example.html)

**Minimal working example:** N/A

### Expected behavior:
x-axis should be period, y-axis should be height

### Screenshots:
![image](https://github.com/user-attachments/assets/184cadc0-b295-495d-b661-79e411ac9c06)

### Desktop (please complete the following information):
 - OS: N/A
 - MHKiT Version: 0.8.1

### Additional context:
N/A

**Comment by ssolson** [comment]
I see. Good catch. I'll switch the labels around. 🙏

**Comment by akeeste** [comment]
Resolved by #360
