### ISSUE TITLE
Spectral Formulations

### ISSUE THREAD

**Issue by kmruehl** [MHKiT-Software/MHKiT-Python#39]
See open issue on WEC-Sim repository related to the IEC specifications for spectra. 
https://github.com/WEC-Sim/WEC-Sim/issues/358

**Comment by ssolson** [comment]
This was closed in WecSim by PR [#365](https://github.com/WEC-Sim/WEC-Sim/issues/365). Kelly what should our proposed path forward on this be?

**Comment by kmruehl** [comment]
@ssolson I recommend we do that same with MHKiT, to update the wave spectrum formulations to follow IEC TS62600-2 standards.
