### ISSUE TITLE
Tidal Plots 

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-Python#85]
Ebb and Flood histograms of probability and exceedance probability. Examples below. 
![Screen Shot 2020-11-23 at 12 19 02 PM](https://user-images.githubusercontent.com/50752018/100005374-140a0280-2d86-11eb-86e0-64aefc336eff.png)

**Comment by ssolson** [comment]
Looks cool! Rebecca, can you get me the data that was used to create these? or did this come from a NOAA buoy? If from a NOAA buoy I can pull the data using the MHKiT function if I now which one.

**Comment by rpauly18** [comment]
I do not know the specific location where this data came from but it was made with the NOAA tides and currents data- so data pulled from any site should suffice to create a general function.

**Comment by ssolson** [comment]
Right I was just hoping to recreate these using the same data if possible. Would be an easy check that I got it right.
