### ISSUE TITLE
FFT feature

### ISSUE THREAD

**Issue by kmruehl** [MHKiT-Software/MHKiT-Python#93]
Feature request from a WEC-Sim user to provide a FFT function and/or example to apply to time-series data. 
https://github.com/WEC-Sim/WEC-Sim/issues/500

**Comment by ssolson** [comment]
I believe scipy has great fft functionality. Ryan sent me a great example using the fft we can include with our examples for our users.

[ocean_waves_via_fft.zip](https://github.com/MHKiT-Software/MHKiT-Python/files/6051411/ocean_waves_via_fft.zip)

**Comment by BinoBK** [comment]
Hi all, Can you please share the script that is mentioned in this thread? 
Thanks,
Bino

**Comment by ssolson** [comment]
> Hi all, Can you please share the FFT script that is mentioned in this thread? Thanks, Bino

Here you go:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.fft.html
