### ISSUE TITLE
Additional WPTO hindcast datasets

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-Python#97]
New Regions have been added to the WPTO hindcast dataset. A new parameter will need to be added to the [hindcast.request_WPTO_point_dataset](https://github.com/MHKiT-Software/MHKiT-Python/blob/master/mhkit/wave/io/hindcast.py) to enable access to that data.

**Comment by ssolson** [comment]
@rpauly18 did we complete this?

**Comment by rpauly18** [comment]
Yes, closing issue
